### PR TITLE
optionally extract raw affiliation string

### LINKED ISSUE #547: Feature request: Extract affiliation text
(I hope I did not raise that before)

We internally came to the conclusion, that we rather extract the affiliation string as text (as it appeared in the document), instead of (or in addition to) being split into separate fields. That is in part due to inconsistencies and information either not being reliable or incomplete.

Maybe having an additional field would be best. Then one can choose whether to use that or the individual fields.

Any thoughts on that?

### PR DESCRIPTION
**Pull request by de-code**
resolves #547 

/cc @kermitt2 

To run and watch related BiblioItemTest tests:

```bash
./gradlew -t grobid-core:test -no-daemon --info --tests \
    org.grobid.core.data.BiblioItemTest
```

### CODE REVIEW

**Comment by de-code** [comment]
There was a separate "Fail Affiliations" code branch that I missed out. I compared the lines and they seemed identical. That's why I also refactored it to a separate method (`appendAffiliation`).

**Comment by lfoppiano** [comment]
Here one result example for the article: ``Elephant: Sequence Labeling for Word and Sentence Segmentation``

```
<author>
                            <persName
                                xmlns="http://www.tei-c.org/ns/1.0">
                                <forename type="first">Kilian</forename>
                                <surname>Evang</surname>
                            </persName>
                            <affiliation key="aff0">
                                <note type="raw_affiliation">
                                    <label>*</label> University of Groningen, Oude Kijk in &apos;t Jatstraat 26, 9712 EK Groningen, The Netherlands
                                </note>
                                <orgName type="institution">University of Groningen</orgName>
                                <address>
                                    <addrLine>Oude Kijk in &apos;t Jatstraat 26</addrLine>
                                    <postCode>9712 EK</postCode>
                                    <settlement>Groningen</settlement>
                                    <country key="NL">The Netherlands</country>
                                </address>
                            </affiliation>
                        </author>
```

**Comment by kermitt2** [comment]
Nice work thank you @de-code ! 

I pushed some cosmetic changes to the branch `elifesciences/extract-raw-affiliation-string-fork` after a checkout locally: 

```
git fetch origin refs/pull/549/head
git checkout -b elifesciences/extract-raw-affiliation-string-fork FETCH_HEAD
```

but the commit is not added here :/ It creates an independent branch in this repo. 

So I am going to try to add my changes in the review (hard because my internet connection cut all the time), but these changes are in this local branch too (it's cosmetic because just moving `getLayoutTokensForTokenizedText()` in `LayoutTokensUtil.java`, where it is more relevant and improving the layout of the check boxes in the console demo).  

Less cosmetic, but would be necessary I think:

- update the Web Service documentation `Grobid-service.md` with the `includeRawAffiliations` option (same as `includeRawCitations`)... boring I know :D

- remove the second argument of the method:

`public String toTEIAuthorBlock(int nbTag, boolean withCoordinates, GrobidAnalysisConfig config)`

because the `withCoordinates` is now available in the `config` object, so it does not make sense to have it as independent boolean parameter. 
It is given from `config` by:

```
withCoordinates = config.getGenerateTeiCoordinates().contains("persName");
```

**Comment by de-code** [comment]
Hi @kermitt2

Thank you for reviewing the code and suggesting changes. Seems to all make sense.

It sounds like you already made the changes locally. I wasn't sure whether you were going to try to push the changes again? (I am assuming it wasn't a permission issue?)

**Comment by kermitt2** [comment]
I was not able to input a review, so I pushed in a local branch `elifesciences/extract-raw-affiliation-string-fork` (I guess I should have pushed to `https://github.com/elifesciences/grobid/tree/extract-raw-affiliation-string-fork` to have the changes visible here directly, but I can't of course). 
Not sure how to proceed (you could see my changes on the local branch and modify your fork? re-open a PR?).

**Comment by de-code** [comment]
Okay, I understand now. Apologies for being slow. I merged your branch back into this branch so that it is showing up.

I believe you should be able to push to the source PR branch, so long as the author didn't untick `Allow edits from maintainers` when creating a PR.

**Comment by kermitt2** [comment]
So I am going to merge the PR as it is and complete the documentation myself, so that we can move one with the next release, thanks !

**Comment by de-code** [comment]
> So I am going to merge the PR as it is and complete the documentation myself, so that we can move one with the next release, thanks !

Okay, apologies. I missed that with the documentation.

**Pull request merged**
