### PR TITLE
update dependencies to remove known security flaws in dependencies of grobid-service

### PR DESCRIPTION
**Pull request by woodfighter**
not extensively tested yet, not a user just a sysad

### CODE REVIEW

**Comment by lfoppiano** [comment]
Which kind of tests did you run?

**Comment by woodfighter** [comment]
I used [OWASP Dependency-Check](https://owasp.org/www-project-dependency-check/) with default settings.

**Comment by lfoppiano** [comment]
I tested the interface and everything seems fine.

Only issue, but it's common to the master version - and is not due to this PR, is #548

**Comment by lfoppiano** [comment]
I tested #548 using these changes and the problem is not happening.

**Pull request merged**
