### PR TITLE
Update jquery to version > 3.5.0 to avoid XSS + bibtex fix

### PR DESCRIPTION
**Pull request by lfoppiano**
This should solve #1023 and #1027

### CODE REVIEW

**Comment by kermitt2** [comment]
Thanks a lot ! It should fix https://github.com/kermitt2/grobid/issues/1027 yes, we'll see for the next docker build.

**Comment by lfoppiano** [comment]
I've created a new branch 0.7.3-fixes and cherry-picked these changes there. 
I think we can build the 0.7.3 docker image again and replace the old one.

**Comment by kermitt2** [comment]
> In the HF space, in the embedded version the bibtex is still returned.. There is something related to the HF stuff that is changing the request from xml to text I think.

With slightly older docker image, it was working, for example https://huggingface.co/spaces/kermitt2/grobid-crf running with 0.7.3.-SNAPSHOT is correctly managing XML for processHeader. I was rather suspecting something with the JDK version (more or less the only thing that changed between the images), but weird in any cases.  

Screenshot from 2023-06-13 08-42-41

**Comment by lfoppiano** [comment]
Sorry, good news.. it's working.. It seems that I did not properly refresh.. 

image

**Comment by kermitt2** [comment]
Cool ! I'll update the full image too.

**Comment by kermitt2** [comment]
It's done for the full image on Docker Hub too, and it works fine on HF.

**Pull request merged**
