### PR TITLE
Rework the way stats are calculated

### PR DESCRIPTION
**Pull request by boumenot**
This may be too big of a change...

I was trying to understand how Grobid evaluates a model, and the best way I found to do that was to refactor the code.  It produces the same results in my *limited* testing.

### CODE REVIEW

**Comment by boumenot** [comment]
No need to apologize.  I too have been busy, and I haven't even addressed the issue caught by CI.

**Comment by kermitt2** [comment]
Apparently two classes missing in the PR - LabelStat.java and Stats.java

**Comment by boumenot** [comment]
Gah!  I'll commit them when I get home.

**Comment by kermitt2** [comment]
Tested on the PMC sample set (~2000 documents) and same results, let's merge, thanks !

**Pull request merged**
