### PR TITLE
Fix fmemopen emulation issue

### PR DESCRIPTION
**Pull request by boumenot**
Thanks to your fix, and with this change the majority of tests now pass.  I am still hitting a JVM crash that I am trying to track down, but hopefully this will allow you to do more.

### CODE REVIEW

**Comment by boumenot** [comment]
I found the last crash, and all of the tests are finally passing.  Give this version a spin, and let me know if it works for you.

```text
Results :

Tests run: 6, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] grobid-parent ...................................... SUCCESS [  0.006 s]
[INFO] grobid-home ........................................ SUCCESS [  1.813 s]
[INFO] grobid-core ........................................ SUCCESS [03:12 min]
[INFO] grobid-trainer ..................................... SUCCESS [  0.664 s]
[INFO] grobid-service ..................................... SUCCESS [ 48.104 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:03 min
[INFO] Finished at: 2016-09-22T22:27:46-07:00
[INFO] Final Memory: 10M/154M
[INFO] ------------------------------------------------------------------------
```

**Comment by lfoppiano** [comment]
It works! 👍 

screen shot 2016-09-23 at 10 50 47

**Comment by lfoppiano** [comment]
I've tested the batch mode and didn't have technical problems. 👍 

Great job @boumenot  :)

**Comment by boumenot** [comment]
w00t!

**Pull request merged**
