### PR TITLE
Updates to the CrossRef requests implementation 

### PR DESCRIPTION
**Pull request by Aazhar**

### CODE REVIEW

**Comment by lfoppiano** [comment]
@Aazhar is this PR related to crossref? Could you check this issue too? #705

**Comment by kermitt2** [comment]
Adding some background about the problem: 

The CrossRef support desk has indicated that the max query rate to follow by the CrossRef client, which is given in the header pf the crossref response is not reliable - at least not reliable anymore, e.g. 50 requests max per second. So we can't use anymore the existing TimedSemaphore implementation which dynamically adapt the query rate of the CrossRef client to the indicated max query rate based on time range.  

They indicated that we need rely only on the total number of active parallel queries that should not go beyond the limit given in the indicated `X-Rate-Limit-Limit`. So the PR uses now a non-bounded `CachedThreadPool` and we check that the limit of allowed active threads/queries is lower than this limit. 

@Aazhar you mentioned `X-LIMIT-LIMIT`, but it's actually still `X-Rate-Limit-Limit` right? We don't capture a `X-LIMIT-LIMIT` in the response currently.

**Comment by lfoppiano** [comment]
Thanks, @kermitt2. Meanwhile, I set this PR as "draft" as it seems not yet ready to be merged

**Comment by kermitt2** [comment]
> Could you check this issue too? #705

#705 is related, yes - this PR fixes a serious issue when scaling, leading possibly to an ever-growing of threads. But with the fixed number of max queries that is introduced now, having ever hanging queries without CrossRef response might fill all the allowed number of threads - so #705 is important to fix too. 

For issue #705 I think we need to check the futures to see if they finished normally or canceled by timeout and re-send the query, it's a bit complicated. I thought there was some default timeout with `CachedThreadPool` but apparently not. 

Of course a good solution is to use biblio-glutton rather than CrossRef :D

**Comment by kermitt2** [comment]
I removed the division of the rate by 2, its not relevant anymore because we are not using the sliding time window for the number of active threads. Keeping it cause the number of threads to be always half of the CrossRef response indicated `X-Rate-Limit-Limit` and processing is simply 2 times longer...

Tested with the 1942 PDF files of the PMC sample with full reference consolidation, runtime is now the same as with the previous `TimedSemaphore` implementation (between 150 and 180 minutes).

**Comment by Aazhar** [comment]
hello @lfoppiano 
regarding #705 , grobid is using a cached thread pool in order to parallelize crossref request, the static Executors.newCachedThreadPool is implemented in the standard Java library:
```java
public static ExecutorService newCachedThreadPool() {
    return new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                                  60L, TimeUnit.SECONDS,
                                  new SynchronousQueue<Runnable>());
}
```

there is a timeout of  60 seconds , so no request should be hanging

**Comment by Aazhar** [comment]
> Tested with the 1942 PDF files of the PMC sample with full reference consolidation, runtime is now the same as with the previous `TimedSemaphore` implementation (between 150 and 180 minutes).

do you know in average how long is the duration of a request thread  for you ?

**Comment by kermitt2** [comment]
I changed the sleep time for a new crossref request thread when the pool is full to `TimeUnit.MICROSECONDS.sleep(10);` after some tests... not super sure because crossref service response time is changing over the day apparently (as my home internet bandwidth), but it seems to improve a bit (by 10-15 minutes for the 90K references).   

The timeout and failure aspects should really be improved, with logging of crossref request timeout, retry, etc.... Currently we are not even sure if all the crossref queries are timing out or really answered as expected (when looking at the TEI files,we see that it is working)... it's overall really very slow when consolidating all references, in particular as compared to biblio-glutton.

**Pull request merged**
