### PR TITLE
Cors configuration

### LINKED ISSUE #226: Parameter for Cross-Origin Resource Sharing
Currently CORS is allowed for any domains by default for all GROBID services. 

Add & support a config parameter for grobid-service to allow or not CORS, and to specify either any domains (*) or some selected domains.

### PR DESCRIPTION
**Pull request by lfoppiano**
This should resolve #226

### CODE REVIEW

**Comment by kermitt2** [comment]
Just tested it, if I didn't make an error, I don't see the CORS info in the response header:

Current master server response headers:
```
HTTP/1.1 200 OK
Date: Sat, 28 Dec 2019 15:10:21 GMT
Content-Type: application/xml; charset=UTF-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Transfer-Encoding: chunked
```

PR server response headers:
```
HTTP/1.1 200 OK
Date: Sat, 28 Dec 2019 15:07:29 GMT
Content-Type: application/xml; charset=UTF-8
Transfer-Encoding: chunked
```

**Comment by Aazhar** [comment]
> Just tested it, if I didn't make an error, I don't see the CORS info in the response header:
> 
> Current master server response headers:
> 
> ```
> HTTP/1.1 200 OK
> Date: Sat, 28 Dec 2019 15:10:21 GMT
> Content-Type: application/xml; charset=UTF-8
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Methods: GET, POST, DELETE, PUT
> Transfer-Encoding: chunked
> ```
> 
> PR server response headers (with CORS default config in `grobid-service/config/config.yaml`):
> 
> ```
> HTTP/1.1 200 OK
> Date: Sat, 28 Dec 2019 15:07:29 GMT
> Content-Type: application/xml; charset=UTF-8
> Transfer-Encoding: chunked
> ```

I tried it with ajax/jquery and it is ok ! , I ll do further tests, something weird..

**Comment by lfoppiano** [comment]
I need to have a look at it again ...

**Comment by lfoppiano** [comment]
Basically this implementation does not return headers if the Origin doesn't match the allowed origin or it's absent... it seems the proper way to do so, but it's not as I remember this thing...

**Comment by kermitt2** [comment]
ah my bad, I didn't put `Origin: http://localhost` in the requesting header indeed! I though `corsAllowedOrigins: "*"` would also match an absent Origin field.  

Adding for instance `Origin: http://localhost` with the default server config works as expected - in the server response header, we have `Access-Control-Allow-Origin: http://localhost
Access-Control-Allow-Credentials: true`.

**Comment by lfoppiano** [comment]
I just added some minor corrections which were stuck in my local branch with 66de8d57eb72130b5b05002222b38f7358971bcb

**Pull request merged**
