### PR TITLE
added annex figures, tables, equations

### LINKED ISSUE #737: Figures and tables in the back / annex section ignored
This is related to #698

Some documents have main figures and supplementary figures.
If in those cases, the segmentation model labels the supplementary figures as `annex`,
then the content is passed separately to the `fulltext` model.
If the `fulltext` then correctly labels it as `figure`, then the figures from the `annex` are not included in the output.

### PR DESCRIPTION
**Pull request by de-code**
resolves #737

### CODE REVIEW

**Comment by de-code** [comment]
I am not quite sure how I managed to increase the coverage without adding tests or deleting code.

**Comment by lfoppiano** [comment]
With the standard model, I cannot see any difference, the "Extended Data Figure 1" is not extracted at all in both cases. 
I've checked the code and the PR looks good to me.

**Review by lfoppiano — APPROVED** [review]

**Comment by de-code** [comment]
I noticed one issue with it, is that the figure ids are reset. e.g. first body figure has the id `fig_0`. Then the first back section / annex figure also has the id `fig_0`.

**Comment by lfoppiano** [comment]
I close this, which is continued on #1215

**Pull request closed without merging**
