### PR TITLE
create training data: log full exception

### PR DESCRIPTION
**Pull request by de-code**
Logs the full exception rather than just the message.

This helped to narrow down #470

### CODE REVIEW

**Comment by de-code** [comment]
> could you please remove the `+ exp`? We don't need it.
> Something like this:
> `LOGGER.error("An error occured while processing the following pdf: "+ pdfFile.getPath(), exp);`
> 
> would be enough

I removed the `exp` from the message itself as requested.

**Comment by lfoppiano** [comment]
Thanks, sorry I could have do it when merging but I though it was quicker for you

**Comment by de-code** [comment]
> Thanks, sorry I could have do it when merging but I though it was quicker for you

I wasn't complaining just notifying ;-) I am the right person to make the change.

**Comment by lfoppiano** [comment]
No worries. I haven't though you did... I just really felt lazy to do it myself 😸

**Pull request merged**
