### PR TITLE
added support for environment variable overrides

### PR DESCRIPTION
**Pull request by de-code**
implementation of first option discussed in #480

For example setting `GROBID__HEADER__USE_HEURISTICS=false` results in `grobid.header.use_heuristics: false`.

/cc @kermitt2

### CODE REVIEW

**Comment by de-code** [comment]
> @de-code could you add some documentation? I suggest in https://github.com/kermitt2/grobid-quantities/blob/master/doc/gettingStarted.rst

Thank you. Did you mean to point o a document in the `grobid` repo?

Not sure where it mostly belongs to. Could add it to [Grobid-docker.md](https://github.com/kermitt2/grobid/blob/master/doc/Grobid-docker.md) as it will be most useful there. There is also [Properties.md](https://github.com/kermitt2/grobid/blob/master/doc/Properties.md), just not a lot of information there.

**Comment by lfoppiano** [comment]
mmm I think this is also obsolete 
You can add it in the Docker page  no problem or you can add it in the Getting started and link it from the docker page 
up to you  

> > @de-code could you add some documentation? I suggest in https://github.com/kermitt2/grobid-quantities/blob/master/doc/gettingStarted.rst
> 
> Thank you. Did you mean to point o a document in the `grobid` repo?

I meant a part in the documentation where where you can add it. 

> Not sure where it mostly belongs to. Could add it to [Grobid-docker.md](https://github.com/kermitt2/grobid/blob/master/doc/Grobid-docker.md) as it will be most useful there. 
Yes please :-) 

> There is also [Properties.md](https://github.com/kermitt2/grobid/blob/master/doc/Properties.md), just not a lot of information there.

mmm I think this is also obsolete

**Comment by de-code** [comment]
> > > @de-code could you add some documentation? I suggest in https://github.com/kermitt2/grobid-quantities/blob/master/doc/gettingStarted.rst
> > 
> > 
> > Thank you. Did you mean to point o a document in the `grobid` repo?
> 
> I made a mistake. I meant somewhere in https://grobid.readthedocs.io/en/latest/Grobid-service/
> 
> (Source: https://github.com/kermitt2/grobid/blob/master/doc/Grobid-service.md)

I decided for now not to update [Grobid-service.md](https://github.com/kermitt2/grobid/blob/master/doc/Grobid-service.md) because the main "Configuration" section refers to the `yaml` file which this change actually won't affect.

It probably would be good to have a separate section on the `grobid.properties` somewhere (it makes guest appearances in a few files).

> > Not sure where it mostly belongs to. Could add it to [Grobid-docker.md](https://github.com/kermitt2/grobid/blob/master/doc/Grobid-docker.md) as it will be most useful there.
> 
> Yes, also there is fine. Although you can always link it from the Docker page, to wherever you place it. 

That is where I added it for now.

I also addressed the markdown linting issues that my IDE (Visual Studio Code) highlighted to me. I hope you don't mind.

And I reset the commit history on the branch. I think it was still messed up after the previous change of history.

**Comment by kermitt2** [comment]
Thank you @de-code for the PR and the update of Grobid-docker.md!

**Pull request merged**
