### PR TITLE
Support for Apple ARM M1 

### PR DESCRIPTION
**Pull request by lfoppiano**
This PR add the following: 
 - add the rebuilt binaries of pdfalto, wapiti and jep, for Mac ARM architecture  
 - fix path construction to select the ARM architecture properly

### CODE REVIEW

**Comment by lfoppiano** [comment]
I did not test JEP.

**Comment by lfoppiano** [comment]
I found that that depending on the JVM there might be a problem when recognizing the architecture. 
This will probably happen in many cases. 

In my case I can list the JVMs: 

(jep) Lucas-M1-MacBook-Pro:pdfalto lfoppiano$ /usr/libexec/java_home -V
Matching Java Virtual Machines (5):
    19.0.1 (arm64) "Eclipse Adoptium" - "OpenJDK 19.0.1" /Library/Java/JavaVirtualMachines/temurin-19.jdk/Contents/Home
    17.0.5 (arm64) "Eclipse Adoptium" - "OpenJDK 17.0.5" /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    11.0.17 (arm64) "Eclipse Adoptium" - "OpenJDK 11.0.17" /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home
    1.8.202.03 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
    1.8.0_352 (x86_64) "Eclipse Temurin" - "Eclipse Temurin 8" /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home

and the 1.8 version are x86_64.

**Comment by lfoppiano** [comment]
I've done some tests: 
 - external models: grobid-quantities, grobid-superconductors work fine 
 - tested with JEP and Delft work
    ```
conda create --name jep python=3.9 pip
conda activate jep
conda install -c apple tensorflow-deps -y
which pip
pip install tensorflow-macos
pip install tensorflow-metal
pip install jep
pip install -r ../../delft/requirements.txt
pip3 install numpy --upgrade
```

**Comment by jacksongoode** [comment]
Is there something blocking this merge that I could help to test?

**Pull request merged**
