### PR TITLE
Add flag to sinalize the end of doi data.

### PR DESCRIPTION
**Pull request by zedomel**
Without that flag the document DOI is overwrited by the doi
of citations list.

### CODE REVIEW

**Comment by lfoppiano** [comment]
Hi @zedomel could you please provide me a sample response from crossref ?

**Comment by zedomel** [comment]
Sure @lfoppiano, just give me a moment to prepare it.

**Comment by zedomel** [comment]
Hi @lfoppiano,

Here you will find a sample of [CrossRef response](http://doi.crossref.org/openurl?url_ver=Z39.88-2004&pid=zedomel@gmail.com&rft_id=info:doi/10.1111/j.1467-8659.2007.01100.x&noredirect=true&format=unixref): [pastebin.com](https://pastebin.com/MDKgH8Rj).

Look that this specific bib. reference has a field ```citation_list``` and those fields also contains the field ```doi```. Because of that, the CrossrefUnixrefSaxParser overwrites the previously DOI read from   ```doi_data``` field by the ```dog``` reads subsequently, and the last ```dot``` found takes place.

Here a piece of code where the replace is happening:
```java
public static void correct(BiblioItem bib, BiblioItem bibo) {
        if (bibo.getDOI() != null)
            bib.setDOI(bibo.getDOI());
...
}
```

If we look data of two BiblioItem we have:

bib (Original DOI extracted from PDF: **DOI='10.1111/j.1467-8659.2007.01100.x'**): 

```
BiblioItem{submission_date='null', languageUtilities=org.grobid.core.utilities.LanguageUtilities@7b420819, item=-1, parentItem=null, ISBN13='null', ISBN10='null', title='A Comparison of Methods for Generating Poisson Disk Distributions', publisher='null', nbPages=-1, edition='null', language='en', subtitle='null', publication_date='October 11, 2007', normalized_publication_date=null, editors='null', publisher_website='null', serie='null', ISSN='null', ISSNe='null', volume='null', number='null', month='null', support_type='null', version='null', smallImageURL='null', largeImageURL='null', publisherPlace='null', review='null', keywords=null, subjects=null, categories='null', type='null', typeDescription='null', book_type='null', DOI='10.1111/j.1467-8659.2007.01100.x', inDOI='null', abstract_='Poisson disk distributions have many applications in the field of computer graphics. Besides sampling, Poisson disk distributions are used in object distribution, non-photorealistic rendering and procedural texturing. Over the years, a large number of methods for generating Poisson disk distributions have been proposed, making it difficult to choose the right method for a given application. In this paper, we present a detailed comparison of most techniques for generating Poisson disk distributions. The methods we study include dart throwing, relaxation dart throwing, Lloyd's relaxation, Shade's Poisson disk tiles, tiled blue noise samples, fast hierarchical importance sampling with blue noise properties, edge-based Poisson disk tiles, template Poisson disk tiles, corner-based Poisson disk tiles and recursive Wang tiles for real-time blue noise. Analysing all of these methods within a single framework is one of the major contributions of this work.', authors='Ares Lagae and Philip Dutré', location='null', bookTitle='null', serieTitle='null', pageRange='null', journal='null', volumeBlock='null', institution='null', note='cgf˙1100 14:7 COMPUTER GRAPHICS forum', affiliation='Dept. Comp. Sci., Kath. Univ. Leuven', address='null', country='null', town='null', email='null', pubnum='CGF-xml.cls **DOI: 10.1111/j.1467-8659.2007.01100.x**', keyword='Poisson disk distributions, spectral analysis  ACM CCS: I33 [Computer Graphics]: Picture/Image Generation', phone='null', degree='null', web='null', issue='null', journal_abbrev='null', event='null', abstractHeader='abstract', day='null', locationPublisher='null', dedication='null', submission='null', english_title='null', url='null', uri='null', confidence='null', conf=0.0, e_year='null', e_month='null', e_day='null', s_year='null', s_month='null', s_day='null', a_year='null', a_month='null', a_day='null', authorList=null, editorList=null, affiliationList=null, addressList=null, emailList=null, webList=null, phoneList=null, markers=null, fullAuthors=[Ares Lagae, Philip Dutré], fullEditors=null, fullAffiliations=[Affiliation{name='null', url='null', key='aff0', institutions=[Kath. Univ. Leuven], departments=[Dept. Comp. Sci], laboratories=null, country='null', postCode='null', postBox='null', region='null', settlement='null', addrLine='null', marker='null', addressString='null', affiliationString='null', failAffiliation=false}], reference='null', copyright='null', grant='null', affiliationAddressBlock='null', articleTitle='null', beginPage=-1, endPage=-1, year='null', authorString='null', path='', postProcessEditors=false, crossrefError=true, normalized_submission_date=null, originalAffiliation='null', originalAbstract='null', originalTitle='null', originalAuthors='Ares Lagae and Philip Dutré', originalAddress='null', originalNote='null', originalKeyword='null', originalVolumeBlock='null', originalJournal='null'}
```

bibo (CrossRef **DOI='10.1145/1015706.1015750**):
```
BiblioItem{submission_date='null', languageUtilities=org.grobid.core.utilities.LanguageUtilities@7b420819, item=3, parentItem=null, ISBN13='null', ISBN10='null', title='null', publisher='null', nbPages=-1, edition='null', language='null', subtitle='null', publication_date='2008', normalized_publication_date=null, editors='null', publisher_website='null', serie='null', ISSN='0167-7055', ISSNe='1467-8659', volume='5', number='1', month='03', support_type='null', version='null', smallImageURL='null', largeImageURL='null', publisherPlace='null', review='null', keywords=null, subjects=null, categories='null', type='null', typeDescription='null', book_type='null', **DOI='10.1145/1015706.1015750'**, inDOI='null', abstract_='null', authors='Ares Lagae ; Philip Dutré', location='null', bookTitle='null', serieTitle='null', pageRange='null', journal='Computer Graphics Forum', volumeBlock='5', institution='null', note='null', affiliation='null', address='null', country='null', town='null', email='null', pubnum='null', keyword='null', phone='null', degree='null', web='null', issue='1', journal_abbrev='Computer Graphics Forum', event='null', abstractHeader='null', day='null', locationPublisher='null', dedication='null', submission='null', english_title='null', url='null', uri='null', confidence='null', conf=0.0, e_year='null', e_month='null', e_day='null', s_year='null', s_month='null', s_day='null', a_year='null', a_month='null', a_day='null', authorList=[Ares Lagae, Philip Dutré], editorList=null, affiliationList=null, addressList=null, emailList=null, webList=null, phoneList=null, markers=null, fullAuthors=null, fullEditors=null, fullAffiliations=null, reference='null', copyright='null', grant='null', affiliationAddressBlock='null', articleTitle='A Comparison of Methods for Generating Poisson Disk Distributions', beginPage=382, endPage=129, year='2008', authorString='null', path='', postProcessEditors=false, crossrefError=false, normalized_submission_date=null, originalAffiliation='null', originalAbstract='null', originalTitle='null', originalAuthors='null', originalAddress='null', originalNote='null', originalKeyword='null', originalVolumeBlock='null', originalJournal='null'}
```


See that [A Comparison of Methods for Generating Poisson Disk Distributions](http://dx.doi.org/10.1111/j.1467-8659.2007.01100.x)
and
[Fast hierarchical importance sampling with blue noise properties](http://dx.doi.org/10.1145/1015706.1015750)

are different documents. And the DOI 10.1145/1015706.1015750 if found at the last citation in citation_list with ```doi``` field;
```xml
<citation key="b21_313">
<doi>10.1145/1015706.1015750</doi>
</citation>
```

So, I have added a flag to CrossrefUnixrefSaxParser class to read only DOI inside ```doi_data``` field, it is the DOI of the document.

I hope that it makes sense.

Thanks.

**Comment by lfoppiano** [comment]
Thanks. I haven't answered because I was away for a week. I'll work on it this week.

**Comment by kermitt2** [comment]
Hello! Well spotted @zedomel . When I wrote CrossrefUnixrefSaxParser,java (in 2010 I think!), crossref unixref format was not including bibliographical references. So at that time, the DOI could appear only for the target bibliographical item.

**Pull request merged**
