### PR TITLE
Updates on the build 

### PR DESCRIPTION
**Pull request by lfoppiano**
- update to gradle 7.1.1
- restore the coveralls reports
- various cleanup

### CODE REVIEW

**Comment by lfoppiano** [comment]
The update correctly sent coverage information to coveralls. 

https://coveralls.io/builds/42287325 

The PR is ready for merge 👍

**Comment by kermitt2** [comment]
Cool ! thank you Luca

**Comment by kermitt2** [comment]
Coveralls now break the build:

Screen Shot 2021-08-22 at 09 13 21

**Comment by kermitt2** [comment]
mmm ok after the following commit, it works !

**Pull request merged**
